New add deprecated decorator
Python-SIP/sip pull request #46
Opened 2024-11-05 14:33 UTC by troopa81

Supersedes #45 

- add an optionnal deprecated message to the /Deprecated/ annotation
- write down this message in a @deprecated decorator
- display the message when DeprecationWarning exception is raised in runtime code

It fixes #8

2024-11-18 15:49 UTC, troopa81 commented
May I have a review for this please ? :pray:

2024-11-24 15:16 UTC, philthompson10 requested changes
The `sip` modules implement ABIs that use semantic versioning. The proposed changes break this by changing the signature of `api_deprecated()`.

See how the v12 `api_is_py_method()` and `api_is_py_method_12_8()` functions are handled.

Add new `api_deprecated_12_16()` and `api_deprecated_13_9()` functions that take the additional `const char *message` argument. The existing `api_deprecated()` functions must be unchanged. For v12 the new function must be appended to the `sipAPIDef` structure. For v13 it can replace the `unused_private_2` field.

The parser should raise an exception if `/Deprecated/` is used with a string when an ABI earlier than v12.16 or v13.9 is specified.

The code generator should define the `sipDeprecated()` macro to the implementation appropriate to the ABI version.

Add an appropriate comment to the ABI change history in `sip.h.in` for each ABI.

The new `api_deprecated()` functions should assume a valid string will be passed (ie. the message argument will never be non-`NULL`). Make appropriate changes to the calls to `sip_api_deprecated()` in `apiversions.c` and any other places that a `NULL` value is passed.

I don't like the addition of the `deprecated_message` fields in specification.py. Instead change the definition of the existing `deprecated` fields to be `Optional[str] = None`. When parsing the annotation provide a default message (the same as the ones in the old `api_deprecated()` function) if no explicit message was specified.

In `pyi.py` shouldn't a dummy alternative to `warnings.deprecated` be provided if the import fails?

2024-11-25 16:11 UTC, troopa81 commented
Thanks for your review. I made the modification you requested

> The new api_deprecated() functions should assume a valid string will be passed (ie. the message argument will never be non-NULL). 

You mean NULL, not "non-NULL" ? You want to call the function with a specfic message, right?

> Make appropriate changes to the calls to sip_api_deprecated() in apiversions.c and any other places that a NULL value is passed.

What would be the message to give in those case ? TBH I don't get exactly what is supposed to do this part of the code, just to warn the user it should not use getApi/setPI? To use what instead?

> In pyi.py shouldn't a dummy alternative to warnings.deprecated be provided if the import fails?

from the test I made:
- At runtime, if the decorator is not here, nothing happen
- At linter time (tested with pyright), if I write what you [propose](https://github.com/Python-SIP/sip/pull/45#issuecomment-2434769789), it would no try the second `try` if the first one fail. And worst, If I add a stub implementation, it fails, and doesn't report any error.

2024-11-27 13:12 UTC, philthompson10 requested changes
Nearly there...

You can remove the tests in `sipGetAPI()` and `sipSetAPI()` in `sipbuild/module/12/apiversions.c` that call `sip_api_deprecated()`. 

The documentation for the `/Deprecated/` annotations also need updating (`docs/annotations.rst`). Change `This boolean annotation` to `This optional string annotation`. For the function annotation also append `Any string will be appended to the warning and will normally describe what should be used instead.`.

2024-12-02 09:49 UTC, troopa81 commented on sipbuild/generator/outputs/code/code.py
> +            str_deprecated_message = f'''"{ctor.deprecated}"''' if ctor.deprecated else "NULL"
> I think the double quotes in the eventual message are just noise

We need them in the C++ generated code. If not, we get this message

```
tmp/tmprwsck6z6/deprecatedExample/sipdeprecatedExampleTest.cpp:154:58: error: use of undeclared identifier 'This'
            if (sipDeprecated(sipName_Test, SIP_NULLPTR, This ctor is deprecated, stop using it) < 0)                return SIP_NULLPTR;            sipCpp = new sipTest();
```                                                      ^

2024-12-02 09:57 UTC, troopa81 commented on sipbuild/generator/parser/annotations.py
> +def validate_string(pm, p, symbol, name, value, optional):
Done 1ab57f18a70fc3904a24e23198361e13d44d15ed

2024-12-02 10:05 UTC, troopa81 commented on sipbuild/generator/parser/parser_manager.py
> +                self.parser_error(p, symbol,
Done d4c728f7

2024-12-02 10:12 UTC, troopa81 commented on sipbuild/generator/outputs/pyi.py
> +            deprecated_message = f'"""{klass.deprecated}"""'
Done b0f073b7

2024-12-02 10:14 UTC, troopa81 commented on sipbuild/module/source/12/siplib.c
> +    /*
Done 7a9e37dc

2024-12-02 10:18 UTC, troopa81 commented on sipbuild/module/source/12/siplib.c
> +
Done cee4757c

2024-12-02 10:18 UTC, troopa81 commented on sipbuild/module/source/13/sip_core.c
> +
Done cee4757c

2024-12-02 10:18 UTC, troopa81 commented
Comments have all been treated

2024-12-02 15:53 UTC, philthompson10 commented on sipbuild/generator/outputs/code/code.py
> +            str_deprecated_message = f'''"{ctor.deprecated}"''' if ctor.deprecated else "NULL"
Ok, but the triple single-quotes only need to be a single single-quote. Also `NULL` should be `SIP_NULLPTR` to be consistent.

2024-12-02 16:07 UTC, merged

2024-12-02 16:07 UTC, philthompson10 commented
Thanks for all your work on this.

2024-12-04 07:50 UTC, troopa81 commented
@philthompson10 Thanks for the review

When is it supposed to be released ? in what version?

2024-12-04 08:36 UTC, philthompson10 commented
On 04/12/2024 07:50, Julien Cabieces wrote:
> @philthompson10 Thanks for the review
> 
> When is it supposed to be released ? in what version?

In the new few days.